services:

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: awt_database
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    image: openjdk:17-jdk-slim
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/awt_database
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  mysql_data: